config/routes.rb
Eventutti::Application.routes.draw do
  scope "(:locale)", :locale => /en|de/ do
    devise_for :owners
    devise_for :customers
    devise_for :users, class_name: 'Customer', path: 'customers'

    namespace :public do
      resources :statics, id: /(about|help|contact|terms)/, only: :show
      resources :home, only: :index
      resources :venues, only: [:index, :show] do 
        get 'search/(:page)', action: 'search', on: :collection, as: 'search'
        get 'availability', action: 'availability', on: :member, as: 'availability'
        post 'contact/:id', action: 'contact', on: :collection, as: 'contact'
      end
    end

    namespace :owners do
      resources :venues do
        resources :events
        resources :gallery_images, only: [:create, :destroy]
      end
      resources :gallery_images, only: [:create, :destroy]
      resources :events, only: [:new, :index, :create, :edit, :update, :destroy]
    end
  end

  root to: 'public/home#index'
end

app/views/shared/top_navigation/_anon.html.erb
<% n.group t('global.misc.owners') do %>
  <% n.item t('global.devise.sign_up'), new_owner_registration_path(locale: locale),
    highlights_on: [proc { params[:controller] == 'devise/registrations' && resource_name == :owner }] %>
  <% n.item t('global.devise.sign_in'), new_owner_session_path(locale: locale),
    highlights_on: [proc { params[:controller] == 'devise/sessions' && resource_name == :owner }] %>
<% end %>

<% n.group t('global.misc.customers') do %>
  <% n.item t('global.devise.sign_up'), new_customer_registration_path(locale: locale),
    highlights_on: proc { params[:controller] == 'devise/registrations' && resource_name == :customer } %>
  <% n.item t('global.devise.sign_in'), new_customer_session_path(locale: locale),
    highlights_on: proc { params[:controller] == 'devise/sessions' && resource_name == :customer } %>
<% end %>

app/views/shared/top_navigation/_customer.html.erb
<% n.group current_customer.name do %>
  <% n.item t('global.devise.edit_settings'), edit_customer_registration_path(locale: locale),
    highlights_on: proc { params[:controller] == 'devise/registrations' && resource_name == :customer } %>
  <% n.item t('global.devise.sign_out'), destroy_customer_session_path(locale: locale), link_html: { method: :delete } %>
<% end %>

app/views/shared/top_navigation/_locale.html.erb
<% n.group locale do %>
  <% n.item "en", url_for(params.merge(locale: "en")), highlights_on: proc { locale == "en" } %>
  <% n.item "de", url_for(params.merge(locale: "de")), highlights_on: proc { locale == "de" } %>
<% end %>

app/views/shared/top_navigation/_owner.html.erb
<% n.group current_owner.name do %>
  <% n.item t('global.actions.venue.manage'), owners_venues_path(locale: locale) %>
  <% n.item t('global.actions.event.manage'), owners_events_path(locale: locale) %>
  <% n.item t('global.devise.edit_settings'), edit_owner_registration_path(locale: locale) %>
  <% n.item t('global.devise.sign_out'), destroy_owner_session_path(locale: locale), link_html: { method: :delete } %>
<% end %>