config/routes.rb
Eventutti::Application.routes.draw do
  scope "(:locale)", :locale => /en|de/ do
    devise_for :owners
    devise_for :customers
    devise_for :users, class_name: 'Customer', path: 'customers'

    namespace :public do
      resources :statics, id: /(about|help|contact|terms)/, only: :show
      resources :home, only: :index
      resources :venues, only: [:index, :show] do 
        get 'search/(:page)', action: 'search', on: :collection, as: 'search'
        get 'availability', action: 'availability', on: :member, as: 'availability'
        post 'contact/:id', action: 'contact', on: :collection, as: 'contact'
      end
    end

    namespace :owners do
      resources :venues do
        resources :events
        resources :gallery_images, only: [:create, :destroy]
      end
      resources :gallery_images, only: [:create, :destroy]
      resources :events, only: [:new, :index, :create, :edit, :update, :destroy]
    end
  end

  root to: 'public/home#index'
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :name, :phone, :logo, :address_attributes

  has_many :venues
  has_many :events, through: :venues
  has_many :customers
  has_one :address, as: :addressable
  
  accepts_nested_attributes_for :address

  mount_uploader :logo, ImageUploader

  delegate :can?, :cannot?, :to => :ability
  
  def ability(options = {:reload => false})
    options[:reload] ? _ability : (@ability ||= _ability)
  end
  
  def name
    n = read_attribute(:name)
    n.try { |s| !s.strip.empty?} ? n : "Anon" 
  end

  protected

  def _ability
    OwnerAbility.new(self)
  end
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  attr_accessible :capacity, :name, :description, :size, :default_venue, :main_image,
                  :pricing_attributes, :address_attributes, :gallery_images_attributes,
                  :venue_type_id

  belongs_to :owner
  belongs_to :venue_type
  has_many :events
  has_many :gallery_images
  has_one :address, as: :addressable
  has_one :pricing
  
  mount_uploader :main_image, ImageUploader

  accepts_nested_attributes_for :pricing, :address, :gallery_images

  scope :address_search, lambda { |addr_element|
    # Unicode normalized string (all diacritics removed)
    #normalized_loc = addr_element.try { |a| a.mb_chars.normalize(:kd).gsub(/[^\x00-\x7F]/n, '').to_s }
    addr_element = I18n.transliterate(addr_element.to_s) 
    if addr_element =~ /^(\d{4})/u
      joins(:address).where("addresses.zip = ?", $1)
    elsif addr_element =~ /^([^,]+)/u
      joins(:address).where("addresses.city_transliterated ilike ?", $1)
    else 
       joins(:address)
       .where("addresses.city ilike ?", !addr_element.blank? ? addr_element : "%")
    end
  }

  scope :price_search, lambda { |lo=0, hi=999_999| 
    return scoped if lo.blank? && hi.blank?
    lo = lo.to_i rescue 0
    hi = hi.blank? ? 999_999 : hi.to_i rescue 999_999
    joins(:pricing)
    .where("pricings.full_day BETWEEN ? AND ?", lo, hi)
  }

  scope :date_search, lambda { |date|
    return scoped if (date = date.to_s).blank?
    date = Date.parse date.to_s 
    joins("LEFT JOIN events on events.venue_id = venues.id")
    .where(<<-SQL, date.strftime("%Y-%m-%d"))
            not exists(
            select 1
            from events e
            where e.start_at::date = ?::date
                  and e.venue_id = venues.id)
           SQL
  }

  scope :venue_type_search, lambda { |venue_type_ids|
    return scoped if venue_type_ids.blank?
    joins(:venue_type)
    .where("venue_types.id in (?)", venue_type_ids)
  }
end

app/models/venue_type.rb
class VenueType < ActiveRecord::Base
  attr_accessible :short, :locale_file_index
  has_many :venues

  def name
    I18n.t(locale_file_index)
  end
end

app/controllers/owners/events_controller.rb
class Owners::EventsController < OwnersController
  authorize_resource

  respond_to :js, only: [:new, :edit, :create, :update, :destroy]
  respond_to :json, only: [:index, :update, :destroy]

  def index
    respond_to do |format|
      format.html
      format.json do
        raise :error if params['start'].blank? || params['end'].blank?
        @start = Time.at(params['start'].to_i).to_date
        @end = Time.at(params['end'].to_i).to_date
        @events = events_accessible_by_current_ability.in(@start, @end)
        @once = @events.find_all { |a| a.repeats == 'no' }
        @daily = @events.find_all { |a| a.repeats == 'daily' }
        @weekly = @events.find_all { |a| a.repeats == 'weekly' }
        render 'public/events/index'
      end
    end
  end

  def edit
    @event = events_accessible_by_current_ability.find(params[:id])
    @venues = Venue.accessible_by current_ability
    authorize! :edit, @event

    respond_with @event
  end

  def new
    @event = Event.new(parse_dates(params[:event]))
    @event.repeats = "no"
    @venues = Venue.accessible_by current_ability

    respond_with @event 
  end

  def create
    @event = Event.new(parse_dates(params[:event]))
    @venues = Venue.accessible_by current_ability

    if @event.valid?
      authorize! :create, @event
      @event.save!
    end

    respond_with @event
  end

  def update
    @event = events_accessible_by_current_ability.find(params[:id], readonly: false)
    @venues = Venue.accessible_by current_ability
    authorize! :update, @event

    @event.update_attributes!(parse_dates(params[:event]))
    respond_with @event
  end

  def destroy
    @event = events_accessible_by_current_ability.find(params[:id])
    authorize! :destroy, @event
    @event.destroy
    respond_with @event
  end

  protected

  def events_accessible_by_current_ability
    Event.accessible_by current_ability
  end

  # time is represented in local time, and we remove the offset
  # so it does not jump up (because of the offset) in the ui
  def parse_dates(event_hash)
    if event_hash[:start_at].present?
      t = DateTime.parse(event_hash[:start_at])
      event_hash[:start_at] = (t.utc + t.offset).to_formatted_s(:db)
    end
    if event_hash[:end_at].present?
      t = DateTime.parse(event_hash[:end_at])
      event_hash[:end_at] = (t.utc + t.offset).to_formatted_s(:db)
    end
    event_hash
  end
end

app/controllers/owners/gallery_images_controller.rb
class Owners::GalleryImagesController < OwnersController
  authorize_resource

  def create
    #require 'debugger'; debugger
    success = false
    params[:venue][:gallery_images_attributes].each do |k, v|
      image = GalleryImage.new(v)
      next if image.image.blank?
      image.venue_id = params[:venue][:venue_id]
      authorize! :create, image
      success = image.save 
    end
      
    type, message = nil, nil
    if(success)
      type, message = :notice, t("global.management.creation_successful")
    else
      type, message = :error, t("global.management.error_during_processing")
    end

    if request.xhr?
      flash.now[type] = message 
    else
      flash[type] = message
    end

    respond_to do |r|
      r.js 
      r.html {
        redirect_to :back if !request.xhr?
      }
    end
  end

  def destroy
    @image = GalleryImage.find(params[:id])
    authorize! :destroy, @image

    type, message = nil, nil
    if(@image.destroy)
      type, message = :notice, t("global.management.deletion_successful")
    else
      type, message = :error, t("global.management.error_during_processing")
    end

    respond_to do |r|
      r.js { flash.now[type] = message }
      r.html {
        flash[type] = message
        redirect_to :back 
      }
    end
  end
end

app/controllers/owners/venues_controller.rb
class Owners::VenuesController < OwnersController
  authorize_resource

  def index
    @venues = venues_accessible_by_current_ability

    respond_to do |r|
      r.html { }
    end
  end

  def show
    @venue = venues_accessible_by_current_ability.find(params[:id])
    authorize! :read, @venue

    respond_to do |r|
      if @venue
        r.html { }
      else
        r.html { redirect_to :back, alert: t("global.management.no_such_record") }
      end
    end
  end

  def new
    @venue = Venue.new
    @venue.build_address
    @venue.build_pricing
  end

  def edit
    @venue = venues_accessible_by_current_ability.find(params[:id])
    authorize! :edit, @venue

    respond_to do |r|
      if @venue
        #@gallery_images = @venue.gallery_images
        r.html { }
      else
        r.html { redirect_to :back, notice: t("global.management.no_such_record") }
      end
    end
  end

  def create
    @venue = Venue.new(params[:venue])
    @venue.owner_id = current_owner.id

    respond_to do |r|
      if @venue.save
        flash[:notice] = t("global.management.creation_successful") 
        r.html { redirect_to action: 'show', id: @venue.id }
      else
        flash.now[:error] = t("global.management.error_during_processing")
        r.html { render action: :new }
      end
    end
  end

  def update
    @venue = venues_accessible_by_current_ability.find(params[:id])
    authorize! :edit, @venue

    respond_to do |r|
      if @venue.update_attributes(params[:venue])
        flash[:notice] = t("global.management.update_successful") 
        r.html { redirect_to action: 'show', id: @venue.id }
      else
        flash.now[:error] = t("global.management.error_during_processing")
        r.html { render action: :edit }
      end
    end
  end

  def destroy
    @venue = venues_accessible_by_current_ability.find(params[:id])
    authorize! :destroy, @venue

    respond_to do |r|
      if @venue.try(:destroy)
        flash[:notice] = t("global.management.deletion_successful") 
        r.html { redirect_to action: 'index' }
      else
        flash.now[:error] = t("global.management.error_during_processing")
        r.html { render action: :index }
      end
    end
  end

  protected

  def venues_accessible_by_current_ability
    Venue.accessible_by current_ability
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_filter :authenticate_owner!
end

app/helpers/venue_helper.rb
module VenueHelper
end

app/views/owners/venues/_management_navigation.html.erb
<div id="management_navigation" %>
  <% if action_name == "index" %>
    <%= link_to t("global.actions.back_to_home"), root_path(locale: I18n.locale) %>
  <% else %>
    <%= link_to t("global.actions.back_to_overview"), owners_venues_path(locale: I18n.locale) %>
  <% end %>
  <%= link_to t("global.actions.venue.new"), new_owners_venue_path(locale: I18n.locale), class: 'btn btn-primary pull-right' unless action_name == "new" %>
</div>

app/views/owners/venues/_venue_form_fields.html.erb
<fieldset>
  <legend><%= Venue.model_name.human %></legend>
  <%= v.input :name, required: true %>
  <%= v.input :description, required: true %>
  <%= v.input :capacity, required: true %>
  <%= v.input :size, required: true %>
  <%= v.input :main_image, as: :file, required: false %>
  <%= v.association :venue_type %>
</fieldset>
<fieldset>
  <legend><%= Pricing.model_name.human %></legend>
  <%= v.simple_fields_for :pricing do |p| %>
    <%= p.input :full_day, required: true %>
    <%= p.input :deposit, required: false %>
  <% end %>
</fieldset>
<fieldset>
  <legend><%= Address.model_name.human %></legend>
  <%= render partial: "shared/address_form", locals: { f: v } %>
</fieldset>

app/views/owners/venues/edit.html.erb
<div id="edit">
  <%= error_messages_for @venue %>
  <%= render partial: "owners/gallery_images/upload_form" %>
  <%= render partial: "management_navigation", locals: { action_name: controller.action_name } %>
  <%= simple_form_for @venue, url: owners_venue_path(@venue, locale: I18n.locale),
        method: 'put' do |v| %>
    <%= render partial: "venue_form_fields", locals: { v: v } %>
    <%= link_to t("global.actions.image.edit"), "#", class: "edit-images-link display-block" %>
    <%= v.submit t("global.actions.save") %>
  <% end %>
  <div class="form-actions">
    <%= link_to t('global.actions.cancel'), owners_venues_path(locale: I18n.locale), class: 'btn' %>
  </div>
</div>

app/views/owners/venues/index.html.erb
<div id="management_venue_listing">
  <%= render partial: "management_navigation", locals: { action_name: controller.action_name } %>
  <table class="table table-condensed">
    <tbody>
    <% @venues.each do |v| %>
      <tr>
        <td><%= link_to image_tag(v.main_image.url(:thumb), alt: v.name, class: "thumb"),
              owners_venue_path(id: v.id, locale: I18n.locale) %></td>
        <td><%= link_to v.name, owners_venue_path(id: v.id, locale: I18n.locale) %></td>
        <td>
          <%= link_to t("global.actions.show"), owners_venue_path(id: v.id, locale: I18n.locale) %>
          <%= link_to t("global.actions.edit"), edit_owners_venue_path(id: v.id, locale: I18n.locale) %>
          <%= link_to t("global.actions.delete"), owners_venue_path(id: v.id, locale: I18n.locale),
                method: :delete, confirm: t("global.misc.are_you_sure") %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/owners/venues/new.html.erb
<div id="new">
  <%= error_messages_for @venue %>
  <%= render partial: "management_navigation", locals: { action_name: controller.action_name } %>
  <%= simple_form_for @venue, url: owners_venues_path(locale: I18n.locale), method: 'post' do |v| %>
    <%= render partial: "venue_form_fields", locals: { v: v } %>
    <%= v.submit t("global.actions.create") %>
  <% end %>
  <div class="form-actions">
    <%= link_to t('global.actions.cancel'), owners_venues_path(locale: I18n.locale), class: 'btn' %>
  </div>
</div>

app/views/owners/venues/show.html.erb
<div id="show">
  <%= render partial: "management_navigation", locals: { action_name: controller.action_name } %>
  <table class="table table-condensed">
    <tbody>
      <% [:name, :description, :capacity, :size].each do |attr| %>
        <tr>
          <td><%= Venue.human_attribute_name(attr) %></td>
          <td><%= @venue.read_attribute(attr) %></td>
        </tr>
      <% end %>
        <tr>
          <td><%= Venue.human_attribute_name(:main_image) %></td>
          <td><%= image_tag @venue.main_image.url, alt: @venue.name, class: 'thumb' %></td>
        </tr>
        <tr>
          <td><%= VenueType.model_name.human %></td>
          <td><%= @venue.venue_type.name %></td>
        </tr>
      <% [:full_day, :deposit].each do |attr| %>
        <tr>
          <td><%= Pricing.human_attribute_name(attr) %></td>
          <td><%= @venue.pricing.read_attribute(attr) %></td>
        </tr>
      <% end %>
      <% [:street, :zip, :city, :directions].each do |attr| %>
        <tr>
          <td><%= Address.human_attribute_name(attr) %></td>
          <td><%= @venue.address.read_attribute(attr) %></td>
        </tr>
      <% end %>
        <tr>
          <td><%= t("global.misc.images") %></td>
          <td><%= render partial: "shared/image_gallery" %></td>
        </tr>
    </tbody>
  </table>
  <div class="form-actions">
    <%= link_to t('global.actions.edit'), edit_owners_venue_path(id: @venue.id, locale: I18n.locale),
          class: 'btn' %>
  </div>
</div>