config/routes.rb
Eventutti::Application.routes.draw do
  scope "(:locale)", :locale => /en|de/ do
    devise_for :owners
    devise_for :customers
    devise_for :users, class_name: 'Customer', path: 'customers'

    namespace :public do
      resources :statics, id: /(about|help|contact|terms)/, only: :show
      resources :home, only: :index
      resources :venues, only: [:index, :show] do 
        get 'search/(:page)', action: 'search', on: :collection, as: 'search'
        get 'availability', action: 'availability', on: :member, as: 'availability'
        post 'contact/:id', action: 'contact', on: :collection, as: 'contact'
      end
    end

    namespace :owners do
      resources :venues do
        resources :events
        resources :gallery_images, only: [:create, :destroy]
      end
      resources :gallery_images, only: [:create, :destroy]
      resources :events, only: [:new, :index, :create, :edit, :update, :destroy]
    end
  end

  root to: 'public/home#index'
end

app/views/shared/_address_form.html.erb
<%= f.simple_fields_for :address do |a| %>
  <%= a.input :street, required: true, as: :string %>
  <%= a.input :zip, required: true, as: :numeric %>
  <%= a.input :directions, required: false %>
<% end %>

app/views/shared/_error_messages.html.erb
<div id="error_explanation" class="alert alert-error">
  <a class="close" data-dismiss="alert">×</a>
  <h4><%= error_hash[:sentence] %></h4>
  <ul><%= raw error_hash[:messages].map { |msg| content_tag(:li, msg) }.join %></ul>
</div>

app/views/shared/_footer.html.erb
<footer>
  <ul class="simple_menu">
    <% ['about', 'contact', 'help', 'terms'].each do |e| %>
      <li><%= link_to t("global.statics.#{e}"), public_static_path(locale: locale, id: e) %>
    <% end %>
  </ul>
</footer>

app/views/shared/_header.html.erb
<header>
  <%= link_to image_tag("et_logo_small.png", alt: "eventutti.ch", id: "header_logo"),
        root_path(locale: locale) %>
  <%= render partial: 'shared/top_navigation' %>
</header>

app/views/shared/_image_gallery.html.erb
<div id="venue-details-modal-container" class="display-none"></div>
<ul class="thumbnails">
<% @venue.gallery_images.each do |i| %>
  <li class="span1">
    <%= link_to image_tag(i.image.url(:thumb), alt: i.description), i.image.url,
          class: 'image-link thumbnail' %>
  </li>
<% end %>
</ul>

app/views/shared/_top_navigation.html.erb
<%= semantic_navigation :top_navigation, config: :bootstrap, class: 'nav nav-pills pull-right' do |n| %>
  <% if owner_signed_in? %>
    <%= render partial: 'shared/top_navigation/owner', locals: { n: n, locale: locale } %>
  <% end %>

  <% if customer_signed_in? %>
    <%= render partial: 'shared/top_navigation/customer', locals: { n: n, locale: locale } %>
  <% end %>

  <% if !signed_in? %>
    <%= render partial: 'shared/top_navigation/anon', locals: { n: n, locale: locale } %>
  <% end %>

  <% n.item t('global.statics.about'), public_static_path(id: 'about', locale: locale), 
    highlights_on: [{ controller: 'public/statics', action: 'show', id: 'about' }] %>
  
  <% n.item t('global.statics.contact'), public_static_path(id: 'contact', locale: locale), 
    highlights_on: [{ controller: 'public/statics', action: 'show', id: 'contact' }] %>

  <%= render partial: 'shared/top_navigation/locale', locals: { n: n, locale: locale } %>
<% end %>

app/views/shared/_venue_search.html.erb
<%= form_tag(search_public_venues_path(locale: locale), method: 'get', class: 'form-inline', autocomplete: 'off') do %>
  <%= render partial: 'shared/venue_search/search_inputs' %>
  <%= render partial: 'shared/venue_search/advanced_search' %>
<% end %>