config/routes.rb
Eventutti::Application.routes.draw do
  scope "(:locale)", :locale => /en|de/ do
    devise_for :owners
    devise_for :customers
    devise_for :users, class_name: 'Customer', path: 'customers'

    namespace :public do
      resources :statics, id: /(about|help|contact|terms)/, only: :show
      resources :home, only: :index
      resources :venues, only: [:index, :show] do 
        get 'search/(:page)', action: 'search', on: :collection, as: 'search'
        get 'availability', action: 'availability', on: :member, as: 'availability'
        post 'contact/:id', action: 'contact', on: :collection, as: 'contact'
      end
    end

    namespace :owners do
      resources :venues do
        resources :events
        resources :gallery_images, only: [:create, :destroy]
      end
      resources :gallery_images, only: [:create, :destroy]
      resources :events, only: [:new, :index, :create, :edit, :update, :destroy]
    end
  end

  root to: 'public/home#index'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :first_name, :last_name, :company, :email, :password, :password_confirmation, :remember_me
  
  belongs_to :owner
  has_many :events
  has_one :address, as: :addressable

  def name
    n = "#{first_name} #{last_name}".strip
    n.empty? ? "Anon" : n
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_filter :authenticate_customer!
end

app/views/customers/_links.erb
<%= semantic_navigation :devise_nav, config: :bootstrap, class: 'nav nav-pills' do |n| %>
  <% n.item t('global.devise.sign_in'), new_session_path(resource_name, locale: locale) %>
  <% n.item t('global.devise.sign_up'), new_registration_path(resource_name, locale: locale) %>
  <% n.item t('global.devise.forgot_passwd'), new_password_path(resource_name, locale: locale) %>
<% end %>